### PR TITLE
Avoid crashes from conflicts between BPBReachability and CDVReachability

### PR DESCRIPTION
**Pull request by kornn**
Build https://github.com/SDA-SE/kundenapp-ui/pull/546 including the reference to this fork for _cordova-plugin-network_ (this is the case in the branches' `package.json`, so no need to change anything) 
**with _fotoapp_ as `PLUGIN=` in your local `.env` file.**

Ensure no crashes occur when running the app and at any point changing from or to airplane mode.

### CODE REVIEW

**Review by palatibm — COMMENTED** [review]
App worked and did not crash in Airplane mode. Tested with commit fa3b9e8a0c4d0fdd66685636ab8d41d0fb15c189

**Comment by palatibm** [comment]
img_20180822_130255

**Review by palatibm — APPROVED** [review]

**Comment by petschniIBM** [comment]
@kornn @palatibm this is a public repo since it is forked...

**Review by petschniIBM — APPROVED** [review]
Is working fine now!

**Pull request merged**
